
server:
 port: 4444

spring:
     
  application:
    name: ap-service-gateway
    
  cloud:
    gateway:
      routes:
        - id: stock-Api
          uri: http://localhost:9090/
          predicates:
            - Path=/price/**
            
            
        - id: Cal-Api
          uri: http://localhost:9999/
          predicates:
            - Path=/cal/**
            
